# Linear Algebra with `numpy`
`numpy` is very well [documented](https://docs.scipy.org/doc/numpy/reference/index.html). You can find a list of linear algebra operations in `numpy` [here](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html). A more general and detailed description of linear algebra with `numpy` and `scipy` (which implements same routines) can be found [here](https://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html).

## Simple Example

Following example walks through solving the basic $\bf{A}x=y$ Linear Algebra problem:

In [0]:
import numpy as np

A = np.array([[4.,5.],[-2.,-1.]])
y = np.array([12.,2.])

print "A:"
print A
print "y"
print y

A_inv=np.linalg.inv(A)

print "Inverse of A:"
print A_inv

print "A * A_inverse:"
print np.matmul(A,A_inv)

print "Identity:"
print np.eye(*A.shape)

x= np.matmul(A_inv,y)

print "Solution: x="
print x

print "Check solution: Ax="
print np.matmul(A,x)
print y==np.matmul(A,x)

A:
[[ 4.  5.]
 [-2. -1.]]
y
[ 12.   2.]
Inverse of A:
[[-0.16666667 -0.83333333]
 [ 0.33333333  0.66666667]]
A * A_inverse:
[[  1.00000000e+00   1.11022302e-16]
 [ -5.55111512e-17   1.00000000e+00]]
Identity:
[[ 1.  0.]
 [ 0.  1.]]
Solution: x=
[-3.66666667  5.33333333]
Check solution: Ax=
[ 12.   2.]
[ True False]


## Matrix Elements
Consider an arbitrary matrix $A$:

\begin{equation*}
A_{m,n} = 
 \begin{pmatrix}
  a_{11} & a_{12} & \cdots & a_{1n} \\
  a_{21} & a_{22} & \cdots & a_{2n} \\
  \vdots  & \vdots  & \ddots & \vdots\\
  a_{m1} & a_{m2} & \cdots & a_{mn} 
\end{pmatrix}
\end{equation*}

we define the columns as $a_j=A_{:,j}$:

\begin{pmatrix} 
| & | &  &|\\
a_1 & a_2 & \dots &\ a_n\\
| & | &  &|
\end{pmatrix}

and rows $a^T_i = A_{i,:}$:

\begin{pmatrix} 
- & a^T_1 & -\\
- & a^T_2 & -\\
 & \vdots & \\
- & a^T_3 & -\\
\end{pmatrix}

or in `numpy`:


In [0]:
# Make a random matrix
A = np.random.rand(10,5)

print "A:"
print A
print "A shape:", A.shape

print "A columns:"
for i in range(A.shape[1]):
    print A[:,i]

print "A rows:"
for j in range(A.shape[0]):
    print A[j,:]
    # Note you can also use A[j]

A:
[[ 0.1857658   0.9914786   0.14688488  0.51782651  0.31506233]
 [ 0.46652475  0.45476551  0.32537495  0.90067949  0.74373792]
 [ 0.17517705  0.91227926  0.42609185  0.49649815  0.47567801]
 [ 0.30332228  0.48546445  0.08527051  0.25605728  0.17729048]
 [ 0.75794902  0.87429816  0.63447476  0.30343447  0.35451195]
 [ 0.61749571  0.5754891   0.93561416  0.21249381  0.30292278]
 [ 0.53639015  0.74786813  0.14987921  0.47621104  0.51683194]
 [ 0.50127558  0.06536713  0.87343701  0.23528287  0.37193857]
 [ 0.89439111  0.11185206  0.18611861  0.16051202  0.8963326 ]
 [ 0.12725995  0.10884242  0.19656955  0.96073897  0.9217351 ]]
A shape: (10, 5)
A columns:
[ 0.1857658   0.46652475  0.17517705  0.30332228  0.75794902  0.61749571
  0.53639015  0.50127558  0.89439111  0.12725995]
[ 0.9914786   0.45476551  0.91227926  0.48546445  0.87429816  0.5754891
  0.74786813  0.06536713  0.11185206  0.10884242]
[ 0.14688488  0.32537495  0.42609185  0.08527051  0.63447476  0.93561416
  0.14987921  0.8734

# Matrix Operations

* Transpose: $(A^T)_{ij} = A_{ji}$
* Sum (elementwise): $C_{ij} = A_{ij} + B_{ij}$
* Elementwise product: $C_{ij} = A_{ij} B_{ij}$
* Matrix product: $C=A \cdot B$: $C_{ij} = \sum_{k} A_{ik} B_{kj}$.
   * Note than if size of $A$ is $n \times m$ then $B$ has to be of size $m \times k$ and the resulting matrix will be of size $n \times k$.
   * Good way to visualize product:
    \begin{equation*}
    AB=
\begin{pmatrix} 
- & a_1 & -\\
- & a_2 & -\\
 & \vdots & \\
- & a_m & -\\
\end{pmatrix} 
\begin{pmatrix} 
| & | &  &|\\
b_1 & b_2 & \dots &\ b_n\\
| & | &  &|
\end{pmatrix}=
\begin{pmatrix}
a^T_1b_1 & a^T_1b_2 & \dots & a^T_1b_n\\
a^T_2b_1 & a^T_2b_2 & \dots & a^T_2b_n\\
\vdots & \vdots & \ddots & \vdots \\
a^T_mb_1 & a^T_mb_2 & \dots & a^T_mb_n
\end{pmatrix}
\end{equation*}

In [0]:
A = np.random.rand(5,4) 
print "A:"
print A

print "A Transpose:"
print A.transpose()

B = np.random.rand(5,4) 
print "B:",
print B

print "A+B:"
print A+B

print "A*B:"
print A*B

# For Matrix Multiply we need correct size B
B1 = np.random.rand(4,5) 

print "Matrix Multiply: A (dot) B1:"
print np.matmul(A,B1)

A:
[[ 0.18491739  0.68777588  0.58073559  0.59948235]
 [ 0.57801374  0.88317636  0.00433694  0.00351015]
 [ 0.13678333  0.76358577  0.94153543  0.04827532]
 [ 0.88289194  0.46739869  0.68454506  0.82935157]
 [ 0.61692912  0.17721148  0.2045841   0.02608633]]
A Transpose:
[[ 0.18491739  0.57801374  0.13678333  0.88289194  0.61692912]
 [ 0.68777588  0.88317636  0.76358577  0.46739869  0.17721148]
 [ 0.58073559  0.00433694  0.94153543  0.68454506  0.2045841 ]
 [ 0.59948235  0.00351015  0.04827532  0.82935157  0.02608633]]
B: [[ 0.72156145  0.71474853  0.62502424  0.0853678 ]
 [ 0.65435541  0.27142659  0.38727475  0.3090901 ]
 [ 0.33106467  0.00994667  0.58027143  0.54278978]
 [ 0.75693696  0.45954334  0.24204448  0.15333801]
 [ 0.88844907  0.32457812  0.98870008  0.71044938]]
A+B:
[[ 0.90647884  1.40252441  1.20575983  0.68485014]
 [ 1.23236916  1.15460296  0.39161169  0.31260025]
 [ 0.467848    0.77353244  1.52180686  0.5910651 ]
 [ 1.6398289   0.92694204  0.92658954  0.98268957]
 [ 1.50

## Vector Products

* Dot product: $x\cdot y = x^T y = \sum_{i=1}^n x_i y_i$
* Other product: 
\begin{equation*}
\begin{pmatrix} x_1\\x_2\\ \vdots \\x_m \end{pmatrix} \begin{pmatrix} y_1&y_2& \dots &y_n\end{pmatrix} =
\begin{pmatrix}
x_1y_1 & x_1y_2 & \dots & x_1y_n\\
x_2y_1 & x_2y_2 & \dots & x_2y_n\\
\vdots & \vdots & \ddots & \vdots \\
x_my_1 & x_my_2 & \dots & x_my_n
\end{pmatrix}
\end{equation*}

In `numpy`:

In [0]:
x=np.array([1,2,3])
y=np.array([4,5,6])

print "x (dot) y:"
print np.dot(x,y)

print "Other product:"
print np.outer(x,y)

x (dot) y:
32
Other product:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


## Norms
* $l=1$ Norm: $\parallel x \parallel_1 = \sum_{i=1}^{n}|x_i|$
* $l=2$ Norm: $\parallel x \parallel_2 = \sqrt{\sum_{i=1}^{n}x_i^2}$
* $l=p$ Norm: $\parallel x \parallel_p = \left(\sum_{i=1}^{n}x_i^p\right)^\frac{1}{p}$
* $l=\infty$ Norm: $\parallel x \parallel_\infty = \max_i |x_i|$
* Law of cosines: $x \cdot y = $\parallel x \parallel_2 $\parallel y \parallel_2 \cos{\theta}$

In `numpy`:

In [0]:
x=[1,2,3]
for i in range(10):
    print i,np.linalg.norm(x,i)

0 3.0
1 6.0
2 3.74165738677
3 3.30192724889
4 3.14634628365
5 3.07738488539
6 3.04301026292
7 3.02466260095
8 3.01444333589
9 3.00858868616
